---
- name: fish | install
  package:
    name: fish

- name: fish  | install omf and set theme
  become_user: markus
  shell: "{{ item }}"
  loop:
    - curl -L https://get.oh-my.fish > install
    - fish install --offline=omf.tar.gz
    - omf install simple-ass-prompt
  notify: set_fish_shell