---
- name: fish | install
  package:
    name: fish
    state: present

- name: fish | set shell for user markus
  become: true
  user:
    name: markus
    shell: /usr/bin/fish

- name: fish | clone oh-my-fish
  git:
    repo: https://github.com/oh-my-fish/oh-my-fish.git
    dest: '/tmp/omf'
    clone: yes

- name: fish | install oh-myfish
  become: true
  become_user: markus
  command: /tmp/omf/bin/install -y --offline --noninteractive