---
- name: fish | install
  package:
    name: fish
    state: present

- name: fish | Clone oh-my-fish repo
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes

- name: fish | Install oh-my-fish
  become: true
  become_user: markus
  command: /tmp/omf/bin/install -y --offline --noninteractive

- name: fish | set shell for user markus
  become: yes
  user:
    append: yes
    name: markus
    shell: fish
    groups: nfs,wheel,docker

# - name: fish | set simple-ass-prompt
#   become: true
#   become_user: markus
#   shell: omf install simple-ass-prompt