---
- name: fish | install
  package:
    name: fish
    state: present

- name: fish | Check if oh-my-fish is installed
  stat:
    path: '/etc/omf.installed'
  register: omf

- name: fish | Clone oh-my-fish repo
  git:
    repo: 'https://github.com/oh-my-fish/oh-my-fish'
    dest: '/tmp/omf'
    clone: yes
  when: not omf.stat.exists

- name: Install oh-my-fish
  become: true
  become_user: markus
  command: /tmp/omf/bin/install -y --offline --noninteractive
  with_dict: "{{ 'markus': '/home/' }}"
  when: not omf.stat.exists

- name: Mark oh-my-fish installed with /etc/omf.installed
  file:
    path: /etc/omf.installed
    state: touch