- name: ssh configuration | create .ssh directory
  file:
    path: /home/markus/.ssh
    state: directory
    owner: test
    group: test
    mode: '0700'

- name: ssh configuration | copy config file
  copy:
    src: files/ssh/config
    dest: /home/markus/.ssh/config
    owner: test
    group: test
    mode: '0644'

- name: ssh configuration | copy hosts file
  copy:
    src: files/ssh/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'