# tasks to complete before running roles
- hosts: all
  tags: always
  become: true
  pre_tasks:
    - name: update repos
      tags: always
      pacman:
        update_cache: yes
        upgrade: yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

# run roles
- hosts: markus
  tags: base
  become: true
  roles:
    - markus