---
- hosts: localhost
  connection: local
  become: true

  # pre_tasks:
  #   - name: update repos
  #     pacman:
  #       update_cache: yes
  #       upgrade: yes
  #     changed_when: False

  tasks:
    - include: tasks/software/packages.yml
    - include: tasks/system/autofs.yml
    - include: tasks/system/ssh_config.yml
    - include: tasks/system/user.yml