---
- block:
  # Make sure users exist on the system
  - import_tasks: user/markus.yml

  # Other system setup stuff
  - import_tasks: system/ssh.yml
  - import_tasks: system/autofs.yml
  - import_tasks: system/htop.yml
  - import_tasks: system/fish.yml
  - import_tasks: system/flatpak.yml

  # Install and configure Development tools
  - import_tasks: development/ant.yml
  - import_tasks: development/code.yml
  - import_tasks: development/docker.yml
  - import_tasks: development/git.yml
  - import_tasks: development/python.yml

  # Install and configure gnome
  - import_tasks: gnome/appearance.yml
  - import_tasks: gnome/keybindings.yml
  - import_tasks: gnome/nautilus.yml

  # Install and configure other software
  - import_tasks: software/bitwarden.yml
  - import_tasks: software/zoom.yml
  - import_tasks: software/firefox.yml
  - import_tasks: software/chromium.yml
  - import_tasks: software/gimp.yml
  - import_tasks: software/handbrake.yml
  - import_tasks: software/inkscape.yml
  - import_tasks: software/keepassxc.yml
