---
- name: vscode | install
  package:
    name: code

- name: vscode | set directory for extensions
  become_user: markus
  command: code --extensions-dir /home/markus/.vscode-oss/extensions

- name: vscode | install extensions
  become_user: markus
  command: "{{ item }}"
  loop:
    - code --install-extension MS-CEINTL.vscode-language-pack-de
    - code --install-extension ms-python.python
    - code --install-extension bmewburn.vscode-intelephense-client
    - code --install-extension felixfbecker.php-debug
    - code --install-extension formulahendry.code-runner
    - code --install-extension alefragnani.project-manager
    - code --install-extension Gruntfuggly.todo-tree
    - code --install-extension nickheap.vscode-ant
    - code --install-extension ms-azuretools.vscode-docker
    - code --install-extension lextudio.restructuredtext
    - code --install-extension ziishaned.livereload
    - code --install-extension skyapps.fish-vscode
    - code --install-extension mikestead.dotenv
