---
- name: docker | install
  package:
    name:
      - docker
      - docker-compose

- name: add user markus to docker group
  user:
    name: markus
    append: yes
    groups: docker
  notify:
    - start_docker
    - enable_docker