---
- name: git | Setup default git configuration
  become_user: markus
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "RedfinDiver" }
    - {name: "user.email", value: "redfindiver@gmail.com" }