---
- name: update_xdg
  become_user: markus
  command: /usr/bin/xdg-user-dirs-update

- name: start_docker
  become: yes
  service:
    name: docker
    state: started
  ignore_errors: yes

- name: enable_docker
  become: yes
  service:
    name: docker
    enabled: yes
  ignore_errors: yes

- name: start_cups
  become: yes
  service:
    name: cups
    state: started
  ignore_errors: yes

- name: enable_cups
  become: yes
  service:
    name: cups
    enabled: yes
  ignore_errors: yes