- name: development | install
  package:
    name:
      - code
      - ant
      - docker
      - docker-compose
      - python-pip

- name: python | configure
  pip:
    name: pipenv

- name: git | Setup default git configuration
  become_user: markus
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "RedfinDiver" }
    - {name: "user.email", value: "redfindiver@gmail.com" }
  
- name: ant | install apache-ant-contrib
  become: yes
  command: /usr/bin/pamac build apache-ant-contrib  --noconfirm 

- name: ant | install xml-task.jar
  get_url:
    url: https://sourceforge.net/projects/xmltask/files/xmltask/1.16/xmltask.jar
    dest: /usr/share/java/apache-ant/xmltask.jar
    mode: '0644'

- name: ant | set java version
  become: yes
  command: archlinux-java set java-13-openjdk
  