# - name: development | install
#   package:
#     name:
#       - code
#       - ant
#       - docker
#       - docker-compose
#       - python-pip

# - name: python | configure
#   pip:
#     name: pipenv

- name: git | Setup default git configuraiton
  become: markus
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "RedfinDiver" }
    - {name: "user.email", value: "redfindiver@gmail.com" }
  