# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/markus.yml

  # Other system setup stuff
  - import_tasks: system/ssh.yml
  - import_tasks: system/autofs.yml