- name: autofs | install
  package:
    name: autofs

- name: autofs | copy auto.master
  copy:
    src: autofs/auto.master
    dest: /etc/autofs/auto.master
    owner: root
    group: root

- name: autofs | copy auto.synology
  copy:
    src: autofs/auto.synology
    dest: /etc/autofs/auto.synology
    owner: root
    group: root

- name: autofs | start and enable daemon
  tags: autofs
  service:
    name: autofs
    state: started
    enabled: true